version: '3'
services:
  # hazelcast imdg
  hazelcast:
    image: hazelcast/hazelcast:3.8.1
    volumes:
        - .:/cfg
    environment:
        - JAVA_OPTS=-Dhazelcast.config=/cfg/hazelcast.xml -Dhazelcast.port=5705 -Dgroup.name=hc-farm -Dgroup.password=s3crEt -Dhazelcast.mancenter.url=http://mancenter:8080/mancenter
    ports:
         - 5705:5705
    links:
        - "management-center:mancenter"
  # 2 hazelcast imdg
  hazelcast2:
    image: hazelcast/hazelcast:3.8.1
    depends_on:
        - hazelcast
    volumes:
        - .:/cfg
    environment:
        - JAVA_OPTS=-Dhazelcast.config=/cfg/hazelcast.xml -Dhazelcast.port=5706 -Dgroup.name=hc-farm -Dgroup.password=s3crEt -Dhazelcast.mancenter.url=http://mancenter:8080/mancenter
    ports:
         - 5706:5706
    links:
        - "management-center:mancenter"

  #management center
  management-center:
    image: hazelcast/management-center:latest
    # persisting mancenter users db folder to local disk
    volumes:
        - ~/mancenter3.8:/mancenter-3.8
    environment:
        - MANCENTER_DATA=/mancenter-3.8
        # enable REST interface on management center
        # http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Clustered_REST_via_Management_Center.html
        - JAVA_OPTS=-Dhazelcast.mc.rest.enabled=true
    ports:
        - 8088:8080